### ISSUE TITLE
How to test the RE models

### ISSUE THREAD

**Issue by wangxinyu0922** [zjunlp/HVPNeT#1]
Hi,

I want to test the RE model which you provided. However, I cannot find the correct command to run testing. I read the `run.py` and it seems that the file cannot run testing even if the `--do_test` is activated. Could you provide instructions for testing?

**Comment by flow3rdown** [comment]
Hi,

Thanks for your attention!

Sorry for the lack of content about the separate testing section in the previous version, now it has been updated and you can do test directly.

**Comment by wangxinyu0922** [comment]
Great! Thank you for the help.
