### ISSUE TITLE
关系数据集中object image的获取方案？

### ISSUE THREAD

**Issue by BATFOR** [zjunlp/HVPNeT#10]
作者，您好！

作者提供的多模态关系数据集中，关于object image存在两个文件夹img_detect和image_vg，模型使用image_vg中的数据时效果更好。
img_vg和img_detect获取时方法上的区别是什么？为什么img_vg中的图片比img_detect的图片分辨率大很多，似乎超过原图？

非常感谢您提前提供帮助。 @

**Comment by flow3rdown** [comment]
您好！

感谢您的关注。img_vg是通过[visual grounding](https://github.com/zyang-ur/onestage_grounding)工具抽取的子图，img_detect是通过目标检测工具Faster RCNN抽取的object子图。由于visual grounding与名词短语有关，粒度相比目标检测的object更粗，所以抽取的图片分辨率显得更大。同时考虑原图、img_vg和img_detect是想融入图片不同粒度的信息。

**Comment by BATFOR** [comment]
感谢作者的解答！
