### ISSUE TITLE
What are the details of using the visual grouding tool?

### ISSUE THREAD

**Issue by windygoogle** [zjunlp/HVPNeT#12]
Hi, I noticed in your README that you would first extract the nouns in the text and then perform visual grounding. 

My understanding is to use the nouns in the text as a query and get the corresponding image area by visual grounding. 

However, I have some questions about this: (1) if there is more than one noun, is each noun a separate query or all the nouns are one query; (2) in the relational extraction, I found that there are some data with the same text and the same image, only the head entity or the tail entity is different, but the image region is different for these data, according to what you have done in the README, these data have the same text and image, it should be able to get the same image area.

Anyway, I would like to know the exact details of the visual grounding you performed to solve my two doubts above, thanks a lot, your work is great.

**Comment by flow3rdown** [comment]
Hi,

Thanks for your attention! Your question may be answered as follows: : 
(1) If there is more than one noun, each noun will be queried separately.
(2) During the extraction process, we will consider the head entity nouns and tail entity nouns in the text. Specifically, we will utilize these entity nouns to extract image regions in visual grounding tools, resulting in distinct image regions for the data with the same text and the same image but different head entity or tail entity.

**Comment by windygoogle** [comment]
Thank you!
