### ISSUE TITLE
data preprocess

### ISSUE THREAD

**Issue by wxz2002** [zjunlp/HVPNeT#15]
Hello, could I inquire about how you handle data preprocessing specifically? Is it possible to make the relevant code public?

**Comment by flow3rdown** [comment]
Hi, the details about the data preprocessing are listed [here](https://github.com/zjunlp/HVPNeT/blob/main/README.md#data-preprocess). We will not release the data processing code temporarily, but we have open-sourced the processed data [here](https://github.com/zjunlp/HVPNeT/blob/main/README.md#data-download).
