### ISSUE TITLE
关于MRE任务中F1计算的问题

### ISSUE THREAD

**Issue by 2kjiejie** [zjunlp/HVPNeT#16]
![image](https://github.com/zjunlp/HVPNeT/assets/47802214/65308a70-2252-4e7d-89b9-3bbfcde593b0)

在您文章的数据中，MNER任务的F1计算是2*p*r/(p+r)，但是MRE却不是，请问MRE的F1是有不同的计算方式吗？

**Comment by njcx-ai** [comment]
您好，非常感谢您对我们工作的关注和问题的纠正。这里MNER任务的F1计算是依旧是2pr/(p+r)，最后的F1值与2pr/(p+r)的计算结果基本是一致的哈，其中的差异可能是当初做实验在MRE上调参过程中产生的多个很接近的结果之间出现了误配。实际上您可以放心使用我们的code复现出表中MRE任务上的F1 score。我们也会后续继续更新修正的版本。

**Comment by 2kjiejie** [comment]
好的，谢谢回复！

**Comment by 2kjiejie** [comment]
好的，谢谢回复！
