### ISSUE TITLE
关于 使用 visual grouding 工具提取局部视觉图像的代码实现，能提供一下吗

### ISSUE THREAD

**Issue by lisx123** [zjunlp/HVPNeT#17]
邮箱lizooe@outlook.com

十分感谢

**Comment by flow3rdown** [comment]
您好，我们是基于[visual grounding](https://github.com/zyang-ur/onestage_grounding)工具抽取的子图，可以参考这个issue #12 #10

**Comment by lisx123** [comment]
> 您好，我们是基于[visual grounding](https://github.com/zyang-ur/onestage_grounding)工具抽取的子图，可以参考这个issue #12 #10

那你好，请问你们使用的是哪一个[visual grounding](https://github.com/zyang-ur/onestage_grounding)工具的预训练模型？Flickr30K ？还是RefCOCO？还是另外一个

**Comment by flow3rdown** [comment]
我们使用的是Flickr30K

**Comment by zxlzr** [comment]
请问您还有其他问题吗
