### ISSUE TITLE
关于论文中对比实验的疑问？

### ISSUE THREAD

**Issue by jiaweidoris** [zjunlp/HVPNeT#19]
您好，我想问一下，关于论文中对比实验的MEGA，该文章《Multimodal Relation Extraction with Efficient Graph Alignment》的原文只有多模态关系抽取的实验结果，没有关于MNER的实验数据结果，而且原项目也没有提供关于MNER的数据集处理之后的数据结果（比如imgSG，rel_1等数据），请问您是如何修改代码得到结果的呢？可以提供一下MNER数据集处理之后的结果（比如imgSG，rel_1等数据）吗？

**Comment by njcx-ai** [comment]
您好，非常感谢您对我们工作的关注。关于MEGA在MNER数据上的实验结果是来自于MEGA的源码进行复现，其中MNER的数据集处理流程与MRE是一样的。我们之前的MNER数据集处理之后的结果可能因为服务器的迁移和删容而丢失了，您仍然可以参考MEGA上链接的imgSG的处理代码进行处理。

**Comment by zxlzr** [comment]
请问您还有其它问题吗？如有论文细节或复现任何问题欢迎提issue😊

**Comment by jiaweidoris** [comment]
> 请问您还有其它问题吗？如有论文细节或复现任何问题欢迎提issue😊

感谢你们的工作，一个额外的问题是 请问你们提供的Twitter15数据集是你们修改之后的还是原数据集呢？我看您提供的链接里Twitter15训练集有4000个数据，Twitter17训练集有3373个数据和原数据集一样。但是您附录里数据数量好像不太一样？麻烦您了，第一次接触有些地方理解的不大对。

**Comment by flow3rdown** [comment]
您好，我们提供的数据集是修复以后的数据，您提到的附录里数据数量不一样可以具体描述一下吗？

**Comment by jiaweidoris** [comment]
> 您好，我们提供的数据集是修复以后的数据，您提到的附录里数据数量不一样可以具体描述一下吗？
抱歉，感谢您的耐心，应该是我搞错了
