### ISSUE TITLE
作者您好，请问代码中的prompt_len=4，指的是论文中的哪部分，还有就是aux的图为什么是3，是一张完整图对应3个aux图片的意思嘛

### ISSUE THREAD

**Issue by 1411591326** [zjunlp/HVPNeT#20]

**Comment by 1411591326** [comment]
是MRE任务，谢谢！

**Comment by flow3rdown** [comment]
您好，prompt_len对应论文中visual images的数量； aux图实际是论文中的object image，由于我们会从原图中采样多张不同位置的object image，所以一张完整图会对应多个aux图片

**Comment by 1411591326** [comment]
很感谢您的回复，还有一点小疑问，prompt_len=4可以理解为一张完整图片的四个位置嘛，还是四张完整图片？










七七七
***@***.***






---原始邮件---
发件人: "Lei ***@***.***&gt;
发送时间: 2024年7月11日(周四) 上午10:26
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zjunlp/HVPNeT] 作者您好，请问代码中的prompt_len=4，指的是论文中的哪部分，还有就是aux的图为什么是3，是一张完整图对应3个aux图片的意思嘛 (Issue #20)




 
您好，prompt_len对应论文中visual images的数量； aux图实际是论文中的object image，由于我们会从原图中采样多张不同位置的object image，所以一张完整图会对应多个aux图片

**Comment by flow3rdown** [comment]
prompt_len等于object image的数量+完整图

**Comment by 1411591326** [comment]
还需要麻烦您一下，prompt_guids最后编码结果是bsz,4,3840，这里面的4和3840都表示什么意思，如果这里的4表示原图➕object图的数量，那为什么既有prompt_guids又有aux_prompt_guids呢，麻烦了












七七七
***@***.***






---原始邮件---
发件人: "Lei ***@***.***&gt;
发送时间: 2024年7月11日(周四) 上午10:31
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zjunlp/HVPNeT] 作者您好，请问代码中的prompt_len=4，指的是论文中的哪部分，还有就是aux的图为什么是3，是一张完整图对应3个aux图片的意思嘛 (Issue #20)




 
prompt_len等于object image的数量+完整图

**Comment by njcx-ai** [comment]
您好，这里的4表示的就是原图➕object图的数量，3840表示的是模型embedding层的维度哈。请问您这边aux_prompt_guids最好的编码结果是啥呢

**Comment by 1411591326** [comment]
aux的三个编码都是一样的bsz,4,3840












七七七
***@***.***






---原始邮件---
发件人: "Xiang ***@***.***&gt;
发送时间: 2024年7月11日(周四) 中午12:10
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zjunlp/HVPNeT] 作者您好，请问代码中的prompt_len=4，指的是论文中的哪部分，还有就是aux的图为什么是3，是一张完整图对应3个aux图片的意思嘛 (Issue #20)




 
您好，这里的4表示的就是原图➕object图的数量，3840表示的是模型embedding层的维度哈。请问您这边aux_prompt_guids最好的编码结果是啥呢

**Comment by zxlzr** [comment]
hi, do you have any further questions?

**Comment by 1411591326** [comment]
非常感谢解答！祝您科研顺利！












七七七
***@***.***






---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年7月18日(周四) 晚上10:59
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [zjunlp/HVPNeT] 作者您好，请问代码中的prompt_len=4，指的是论文中的哪部分，还有就是aux的图为什么是3，是一张完整图对应3个aux图片的意思嘛 (Issue #20)




 
hi, do you have any further questions?
