### ISSUE TITLE
训练时每次到epcoh到4的时候，loss就会变为nan

### ISSUE THREAD

**Issue by lwj01** [zjunlp/HVPNeT#22]
环境，版本都和requirements一样，但是每次训练到epcoh=4时，loss就直接变成nan。请问这是什么原因引起的呢？

**Comment by flow3rdown** [comment]
麻烦贴一下您的训练日志、环境信息以及启动脚本

**Comment by lwj01** [comment]
感谢，回复。问题已经解决，是和同学一起调试过程中，他修改了max_seq参数，应该是导致了数据加载的不完整导致值发生了错误。非常感谢回复！





------------------ 原始邮件 ------------------
发件人: Lei Li ***@***.***&gt;
发送时间: 2024年11月16日 17:02
收件人: zjunlp/HVPNeT ***@***.***&gt;
抄送: lwj01 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [zjunlp/HVPNeT] 训练时每次到epcoh到4的时候，loss就会变为nan (Issue #22)
