### ISSUE TITLE
Not putting parameters into optimizer but still trainable

### ISSUE THREAD

**Issue by JinFish** [zjunlp/HVPNeT#5]
In the modules/train.py file, lines 484 and 492 both add parameters to the optimizer, but the parameters for crf and fc are not added to the optimizer, but they can still be trained. As far as I know, if the model parameters are not added to the optimizer it cannot be trained, do you know why?

**Comment by flow3rdown** [comment]
We add the parameters for crf and fc on lines 494-499 in the  modules/train.py file, so crf and fc can be trained.

**Comment by JinFish** [comment]
But the previous parameters all have `parameters.append(params)`, but not after line 499.

**Comment by flow3rdown** [comment]
> But the previous parameters all have `parameters.append(params)`, but not after line 499.

You're right! The`parameters.append(params)` should be added after line 499, otherwise crf and fc will not be trained. Actually, we found this issue before and fixed it but forgot to push it to git. Thanks for your correction.
