### ISSUE TITLE
Twitter15数据集修改部分实体类别

### ISSUE THREAD

**Issue by yf-lyu** [zjunlp/HVPNeT#6]
你好，对比论文中使用的twitter15数据集和其它论文（UMT、MAF...）所使用的数据集存在部分实体类别不一致情况，其中test.txt存在较多修改实体。在数据不一致情况下与其它模型实验结果进行比较是否合适，修改实体类别的意义是什么？

**Comment by njcx-ai** [comment]
您好感谢您的关注，在审稿过程中有审稿人提到twiter15测试集有很多错误，为了更好评估多模态模型的效果，所以我们人工检查并修复了一些错误，比如xxx，放出来的数据集是修复过的版本，论文里的结果是根据老版本的测试集和训练集，其包含非常多的错误也很难准确对比不同的模型，我们也在修复后的test重跑了基线和我们的模型，效果还不错，这里也非常建议您使用新的测试集（可能仍有部分错误）

**Comment by yf-lyu** [comment]
> 

Thank you very much for your answer, 
Wish you a happy life！

**Comment by njcx-ai** [comment]
您好感谢您的关注，在审稿过程中有审稿人提到twiter15测试集有很多错误，为了更好评估多模态模型的效果，所以我们人工检查并修复了一些错误（比如部分实体不存在B-xxx标签，只包含l-xxx标签以及部分实体标签错误），放出来的数据集是修复过的版本，论文里的结果是根据老版本的测试集和训练集，其包含非常多的错误也很难准确对比不同的模型，我们也在修复后的test重跑了基线和我们的模型，效果还不错，这里也非常建议您使用新的测试集（可能仍有部分错误）。

**Comment by Chenfeng1271** [comment]
你好  请问有按照以当前格式记录的原来数据集的train.txt, dev.txt和test.txt么，因为UMT的数据格式和这个大不一样，我想训练一下以达到论文中的结果，谢谢。

**Comment by zxlzr** [comment]
您好，非常抱歉转换过的老数据我们没有存，您可以自行转换下格式。另外15这个数据噪音比较大建议您直接用17复现起来比较容易。
