### ISSUE TITLE
Twitter15_ckpt, Twitter17_ckpt,re_ckpt需要访问权限

### ISSUE THREAD

**Issue by 2021wangkai** [zjunlp/HVPNeT#8]
您好，Twitter15_ckpt, Twitter17_ckpt,re_ckpt显示谷歌云盘需要访问权限，请问有别的渠道下载吗

**Comment by zxlzr** [comment]
您好因为存储空间大小问题我们现在不提供模型checkpoint下载了非常抱歉，您可以自行训练模型，有问题欢迎提issue

**Comment by 2021wangkai** [comment]
好的，谢谢回复！
