### ISSUE TITLE
Question about get_visual_prompt

### ISSUE THREAD

**Issue by 257556227** [zjunlp/HVPNeT#9]
Great works, but I hava some questions.
1. **prompt_guids**  is 4 * [bsz, 256, 2, 2]. Shouldn't the dimension of torch.cat(prompt_guids, dim=1)  is [bsz, 1024, 2, 2], but it's [bsz, 3840, 2, 2] in fact.
```
prompt_guids, aux_prompt_guids = self.image_model(images, aux_imgs)  # [bsz, 256, 2, 2], [bsz, 512, 2, 2]....
prompt_guids = torch.cat(prompt_guids, dim=1).view(bsz, self.args.prompt_len, -1)   # bsz, 4, 3840
```

2. What does this code do? Is it just calculating the k,v values of superimposing four resnet blocks onto that self-attention layer?
```
for i in range(4):
     key_val = key_val + torch.einsum('bg,blh->blh', prompt_gate[:, i].view(-1, 1), split_prompt_guids[i])
```

3. Why choose 64?
`key, value = key_val[0].reshape(bsz, 12, -1, 64).contiguous(), key_val[1].reshape(bsz, 12, -1, 64).contiguous()  # bsz, 12, 4, 64`

4. If I want to switch to roberta plm, where I need to modiy?
I met 

> `IndexError: index out of range in self`

  File "E:\deeplearning\Anaconda3\envs\py36\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\deeplearning\Anaconda3\envs\py36\lib\site-packages\transformers\models\roberta\modeling_roberta.py", line 846, in forward
    past_key_values_length=past_key_values_length,
  File "E:\deeplearning\Anaconda3\envs\py36\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\deeplearning\Anaconda3\envs\py36\lib\site-packages\transformers\models\roberta\modeling_roberta.py", line 132, in forward
    token_type_embeddings = self.token_type_embeddings(token_type_ids)
  File "E:\deeplearning\Anaconda3\envs\py36\lib\site-packages\torch\nn\modules\module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "E:\deeplearning\Anaconda3\envs\py36\lib\site-packages\torch\nn\modules\sparse.py", line 160, in forward
    self.norm_type, self.scale_grad_by_freq, self.sparse)
  File "E:\deeplearning\Anaconda3\envs\py36\lib\site-packages\torch\nn\functional.py", line 2044, in embedding
    return torch.embedding(weight, input, padding_idx, scale_grad_by_freq, sparse)
IndexError: index out of range in self

### in bert_output = self.bert(input_ids=input_ids,
                            attention_mask=prompt_attention_mask,
                            token_type_ids=token_type_ids,
                            past_key_values=prompt_guids,
                            return_dict=True)

I guess the num_embeddings of bert is 30522, but roberta is 50265

**Comment by flow3rdown** [comment]
Thanks for your attention!

> 1. prompt_guids is 4 * [bsz, 256, 2, 2]. Shouldn't the dimension of torch.cat(prompt_guids, dim=1) is [bsz, 1024, 2, 2], but it's [bsz, 3840, 2, 2] in fact.

Actually, **prompt_guids** is [[bsz, 256, 2, 2], [bsz, 512, 2, 2],  [bsz, 1024, 2, 2],  [bsz,2048, 2, 2]], so the dimension of concatenation is [bsz, 3840, 2, 2].

> 2. What does this code do? Is it just calculating the k,v values of superimposing four resnet blocks onto that self-attention layer?
>```
>for i in range(4):
>    key_val = key_val + torch.einsum('bg,blh->blh', prompt_gate[:, i].view(-1, 1), split_prompt_guids[I])
>```

The goal of this code is to use the dynamic gates(prompt_gate) to aggregate hierarchical image features(split_prompt_guids) to obtain the visual prefix(key, values).

> 3. Why choose 64?

We use `bert-base-uncased` as the PLM, which has 768 hidden size and 12 attention heads, so the size of each attention head is`768 / 12 = 64`.

> 4. If I want to switch to roberta plm, where I need to modify?

You need to modify the  source code `modeling_roberta.py` like `models/modeling_bert.py`. For example, set `past_key_values_length=0` before `embedding_output = self.embeddings(...)`. For other places that need to be modified, please refer to the content annotated with `#add` in `models/modeling_bert.py`.

**Comment by 257556227** [comment]
Thank you very much for your answer,
Wish you a happy life！
